### ISSUE TITLE
Check for OTHER FIDO2 sticks

### ISSUE THREAD

**Issue by nursoda** [Nitrokey/nitrokey-webupdate#10]
I play with different FIDO2-Tokens. I have a [SOMU](https://www.crowdsupply.com/solokeys/somu) installed permanently. I followed the update instructions and inserted the Nitrokey FIDO2 while SOMU still being installed, expecting the updater to detect and select the Nitrokey, and reading its data. Instead, I get this:

```Firefox 78.0 on Linux 64-bit (WebAuthn supported)
Connected Nitrokey FIDO2 firmware version: 3.0.0
Latest Nitrokey FIDO2 firmware version: 2.0.0.nitrokey
Device state: normal mode
Connected device: Nitrokey FIDO2
Update application status: (4) Inspection finished
```

Well…you really should make sure reading data from a device you want to update! If SOMU would have been <2.0, would the updater have tried to flash SOMU?

**Comment by szszszsz** [comment]
Hi @nursoda !
Interesting case. Indeed webupdate was not designed for multiple devices. What's more, Webauthn does not allow to select devices AFAIR (like e.g. WebUSB), but the request is simply sent to all devices connected (this could be worked around perhaps by prefixing data with requested device id).
To sum up, please remove all other FIDO U2F / FIDO2 devices to run the Nitorkey FIDO2 update.

About the flashing, I have obviously not tested that, but it would not work due to following:
- AFAIK bootloader on Somu has to be executed manually by touching buttons on insertion, so it's not possible accidentally;
- AFAIR there is some bootloader check just before flashing starts, which would fail probably (Nitrokey FIDO2 has extended bootloader commands);
- device would certainly fail to verify firmware signature on boot, thus it would remain in the bootloader waiting for the current proper Somu firmware and allow flashing again - it's not possible to cross-flash in other words. 

Will make sure the supported devices list, and the other FIDO devices removal notice will be shown (#11).
